### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by Raffaelbdl** [MathisFederico/LearnRL#123]
`metrics = [
        "exploration~exp.last",
        ("reward~rwd", {"episode": "sum"}),
        "dt_step~",
        "loss"
    ]`

display : 
![image](https://user-images.githubusercontent.com/67725350/111354994-330b0800-8687-11eb-9f21-f54fb96b301c.png)

**Comment by MathisFederico** [comment]
dt_step should be at the end for now, I'll add a fix to strange logger behaviors soon

**Comment by MathisFederico** [comment]
> 
> 
> `metrics = [ "exploration~exp.last", ("reward~rwd", {"episode": "sum"}), "dt_step~", "loss" ]`
> 
> display :
> ![image](https://user-images.githubusercontent.com/67725350/111354994-330b0800-8687-11eb-9f21-f54fb96b301c.png)

I can't seem to be able to reproduce that behavior, could you give more details ?
