### ISSUE TITLE
Fix relative links in documentation

### ISSUE THREAD

**Issue by MathisFederico** [MathisFederico/LearnRL#73]

**Comment by tanweeralii** [comment]
Hey I would like to contribute to this issue

**Comment by MathisFederico** [comment]
> Hey I would like to contribute to this issue

With pleasure ! You can fork the repository, then create a branch named 'bugfix/docs-relative-links' on your forked repository, then do a merge request on the dev branch of the main repository !

Do you know how to fix this ? For that you will need basic knowledge of restructuredText !
Then you can go through the documentation and look for cross-reference links that doesn't work and fix them (by looking at the ones who does work for example !)

Thank you in advance for your help !

**Comment by tanweeralii** [comment]
Yeah I got it. Thanks

**Comment by MathisFederico** [comment]
> Yeah I got it. Thanks

I you have some questions, do not hesitate to ask on our newly built discord !
https://discord.gg/sETxKW6

**Comment by tanweeralii** [comment]
Great! sure
